buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
  }
  dependencies {
    classpath("org.springframework.boot:spring-boot-gradle-plugin:3.5.6")
  }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'jacoco'

group = 'de.gessnerfl'
description = """Fake SMTP Server :: Simple SMTP Server which stores emails in memory and lists email in a web ui"""

ext.scmUrl = 'https://github.com/JavaSaBr/fake-smtp-server.git'
ext.projectUrl = 'https://github.com/JavaSaBr/fake-smtp-server'

repositories {
  mavenCentral()
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

dependencies {
  implementation platform(libs.spring.boot.dependencies)
  implementation libs.spring.boot.starter.actuator
  implementation libs.spring.boot.starter.web
  implementation libs.spring.boot.starter.thymeleaf
  implementation libs.spring.boot.starter.data.jpa
  implementation libs.spring.boot.starter.mail

  implementation libs.commons.io
  implementation libs.subethasmtp
  implementation libs.flyway.core
  implementation libs.thymeleaf.extras.springsecurity
  //implementation libs.jaxb.impl
  implementation libs.jquery
  implementation libs.materializecss
  implementation libs.material.design.icons
  implementation libs.jakarta.validation.api
  implementation libs.hibernate.validator

  compileOnly libs.lombok

  runtimeOnly libs.h2database
  runtimeOnly libs.spring.boot.devtools

  testImplementation platform(libs.spring.boot.dependencies)
  testImplementation libs.spring.boot.starter.test
  testImplementation libs.spring.security.test
  testImplementation libs.commons.lang3
  testImplementation libs.asm
  testImplementation libs.junit.api
  testImplementation libs.junit.jupiter.params

  testCompileOnly libs.lombok
  testRuntimeOnly libs.junit.engine
  testRuntimeOnly libs.junit.platform.launcher

  annotationProcessor libs.lombok
  //annotationProcessor libs.spring.boot.configuration.processor
}

test {
  useJUnitPlatform()
  failOnNoDiscoveredTests = false
}

tasks.register("sourcesJar", Jar) {
  dependsOn "classes"
  group "build"
  archiveClassifier = "sources"
  archiveBaseName = jar.archiveBaseName
  from sourceSets.main.allSource
}

tasks.register("javadocJar", Jar) {
  dependsOn "javadoc"
  group "build"
  archiveClassifier = "javadoc"
  archiveBaseName = jar.archiveBaseName
  from javadoc.destinationDir
}

artifacts {
  archives sourcesJar
  archives javadocJar
}

javadoc {
  failOnError = false
}

bootJar {
  archiveBaseName = 'fake-smtp-server'
}

wrapper {
  gradleVersion = '9.1.0'
  distributionType = Wrapper.DistributionType.ALL
}